CREATE TABLE quote_drafts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES users(id),
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  name VARCHAR(120) NOT NULL DEFAULT '셀프 견적',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_quote_drafts_status CHECK (status IN ('ACTIVE', 'ORDERED', 'ARCHIVED'))
);

CREATE UNIQUE INDEX ux_quote_drafts_active_user
  ON quote_drafts(user_id)
  WHERE status = 'ACTIVE' AND deleted_at IS NULL;

CREATE INDEX idx_quote_drafts_user_status ON quote_drafts(user_id, status);
CREATE INDEX idx_quote_drafts_deleted_at ON quote_drafts(deleted_at);

CREATE TABLE quote_draft_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  quote_draft_id BIGINT NOT NULL REFERENCES quote_drafts(id),
  part_id BIGINT NOT NULL REFERENCES parts(id),
  category VARCHAR(50) NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  unit_price_at_add INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_quote_draft_items_category CHECK (category IN ('CPU', 'GPU', 'RAM', 'MOTHERBOARD', 'STORAGE', 'PSU', 'CASE', 'COOLER')),
  CONSTRAINT chk_quote_draft_items_quantity CHECK (quantity BETWEEN 1 AND 9),
  CONSTRAINT chk_quote_draft_items_unit_price CHECK (unit_price_at_add >= 0)
);

CREATE UNIQUE INDEX ux_quote_draft_items_active_category
  ON quote_draft_items(quote_draft_id, category)
  WHERE deleted_at IS NULL;

CREATE INDEX idx_quote_draft_items_draft_id ON quote_draft_items(quote_draft_id);
CREATE INDEX idx_quote_draft_items_part_id ON quote_draft_items(part_id);
CREATE INDEX idx_quote_draft_items_deleted_at ON quote_draft_items(deleted_at);
